version: '3'
services:
  nginx:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - '80:80'
  api-0:
    build:
      context: ./api
      dockerfile: Dockerfile
  api-1:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
  api-2:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '8082:8080'
